### ISSUE TITLE
还不能部署使用哇？

### ISSUE THREAD

**Issue by xewn** [langhuihui/monibuca#1]
我想搭建一个完整的视频直播场景，企业内的摄像头使用。可以手机APP实时播放摄像头视频就行。谢谢。我用abp vnext开发。

**Comment by langhuihui** [comment]
可以部署使用的，我自己一直在用的啊，你参考文档的说明步骤来做，有什么问题吗？

**Comment by xewn** [comment]
没有问题的哈，我没仔细看，明天我试试呢，谢谢。遇到问题再请教。
