### ISSUE TITLE
部署文档

### ISSUE THREAD

**Issue by wangjuelong** [langhuihui/monibuca#10]
目前部署好像是在线部署，能否提供离线部署文档？另外集群部署如何进行？

**Comment by langhuihui** [comment]
现已提供编译好的二进制文件，直接可以运行

**Comment by lvzhigao** [comment]
是否能够提供FreeBSD下的编译选项，目前部署存在如下报错：
[root@kaifa /extdisk/monibuca-3.0]# go build

go: github.com/Monibuca/engine/v3@v3.3.16: Get "https://proxy.golang.org/github.com/%21monibuca/engine/v3/@v/v3.3.16.mod": dial tcp 172.217.160.113:443: i/o timeout

经查看.github/workflows/go.yml文件，未发现兼容FreeBSD的选项，不知此判断是否成立，请指导。

**Comment by langhuihui** [comment]
你这个错误是需要设置GOPROXY环境变量所致
