### ISSUE TITLE
有没有办法针对单路流进行流量统计？

### ISSUE THREAD

**Issue by shushenghong** [langhuihui/monibuca#100]
找了下文档，好像没找到

**Comment by langhuihui** [comment]
有的，在 summary 接口里面会返回流的信息，里面包含 BPS

**Comment by shushenghong** [comment]
根据bps码率怎么转换为一段时间内消耗的流量譬如MB GB呢？有办法直接获取流量么

**Comment by langhuihui** [comment]
没有统计，理论上可以统计的

**Comment by langhuihui** [comment]
考虑在下一个大版本中增加码率的记录，比如写入时序数据库，方便按照时间窗口进行统计
