### ISSUE TITLE
webtransport 拉流提示握手失败

### ISSUE THREAD

**Issue by moweng** [langhuihui/monibuca#101]
1、报错
![image](https://github.com/langhuihui/monibuca/assets/8938428/fec4e34a-3ac1-4403-8f3d-15bb819608a1)
2、配置
在conf目录下新增了一个webtransport.yaml 文件，对应的配置如下
![image](https://github.com/langhuihui/monibuca/assets/8938428/68baefad-ab81-498c-8b98-ffdebe918fd6)
请问是哪个环节有问题？

**Comment by langhuihui** [comment]
有没有配置 host

**Comment by moweng** [comment]
> 有没有配置 host

![image](https://github.com/langhuihui/monibuca/assets/8938428/0b14ad8d-f1af-43ff-a069-1d89f9a5d168)
通过https 可以正常拉流，选择webtransport行不通

**Comment by moweng** [comment]
> > 有没有配置 host
> 
> ![image](https://user-images.githubusercontent.com/8938428/273422734-0b14ad8d-f1af-43ff-a069-1d89f9a5d168.png) 通过https 可以正常拉流，选择webtransport行不通

补充：preview 页面通过8443端口可以访问，但是webtransport的4433端口看起来是没有启动的，是证书没有配置正确？这里面的证书需要自己下载吗，还是程序内置了，windows 系统，下载的版本
![image](https://github.com/langhuihui/monibuca/assets/8938428/670746fe-1989-44a3-94b2-249eb222871f)
![image](https://github.com/langhuihui/monibuca/assets/8938428/c0294690-e725-4926-96f4-fa250971f903)

日志：

[2023-10-08T11.log](https://github.com/langhuihui/monibuca/files/12839681/2023-10-08T11.log)

**Comment by langhuihui** [comment]
嗯，本地没有证书文件导致的

**Comment by langhuihui** [comment]
我来修改一下

**Comment by moweng** [comment]
另外想了解下，目前支持webtransport 推流吗
