### ISSUE TITLE
关于发布"live/test"流时的timeout问题

### ISSUE THREAD

**Issue by ycRose** [langhuihui/monibuca#102]
作者您好：

我目前在arm64平台上使用m7s可执行文件运行monibuca时，遇到一个小小的问题：在我的程序初始化开始后，monibuca在我还没有真正准备好进行推流的时候，显示"live/test"流已经timeout并且RTSPPublisher关闭了。
15:37:43        INFO    created {"stream": "live/test"}
15:37:43        INFO    publish {"stream": "live/test", "type": "RTSPPublisher"}
15:37:43        INFO    ⌛->🟡   {"stream": "live/test", "action": "publish"}
15:37:43        INFO    no audio track  {"stream": "live/test", "type": "RTSPPublisher"}
15:37:43        INFO    set track       {"stream": "live/test", "type": "RTSPPublisher", "name": "h264"}
15:37:48        WARN    no tracks       {"stream": "live/test"}
15:37:48        INFO    🟡->🔴   {"stream": "live/test", "action": "timeout"}
15:37:48        INFO    stop    {"stream": "live/test", "type": "RTSPPublisher", "conn": "closed"}

**有没有什么方法或者参数设置能使得"live/test"流等待video track attached的时间变长或者持续等待呢？**

我尝试过一些config.yaml中的一些参数，但是好像不奏效：
publish:
publishtimeout: 0 
idletimeout: 0 
delayclosetimeout: 0 
waitclosetimeout: 0 
subscribe:
waittimeout: 50s

如果有解决办法或者任何建议麻烦不吝赐教，谢谢。

**Comment by langhuihui** [comment]
你推流是自己写的逻辑？
