### ISSUE TITLE
m7s这个二进制文件可以后台运行吗

### ISSUE THREAD

**Issue by Johonnyr** [langhuihui/monibuca#103]
大佬好，想通过程序控制monibuca的启停，但是测试时发现总是会占一个启动窗口，请问m7s这个文件是否可以后台运行呢

**Comment by langhuihui** [comment]
m7s就是一个普通的二进制程序，你可以直接问 chatgpt

**Comment by Johonnyr** [comment]
OK，是我犯傻了，感谢大佬
