### ISSUE TITLE
官网的Windows版本下载后exe无法运行

### ISSUE THREAD

**Issue by zhang852774731** [langhuihui/monibuca#105]
下载官网地址提供的Windows版本，运行exe报错。
![1698646509277](https://github.com/langhuihui/monibuca/assets/6835841/7c17aba2-38d1-4fe9-8d57-1e8af50cba29)

**Comment by langhuihui** [comment]
你是什么版本的 windows，尝试一下管理身份运行

**Comment by zhang852774731** [comment]
win10专业版，管理员身份试过，同样的错误

**Comment by zhang852774731** [comment]
可以了，有可能跟360杀毒有关
360提示exe为木马病毒
