### ISSUE TITLE
赞助monibuca会有额外的技术支持或功能定制么

### ISSUE THREAD

**Issue by RanSatious** [langhuihui/monibuca#110]
如题，公司有笔经费用于在流媒体技术上的投入，经过前期的调研，monibuca是我们的候选之一。
但考虑到目前monibuca的体量和使用率，如果被用于生产环境，应该会有不少问题暴露出来。
我们希望以直接对monibuca进行付费或者赞助的方式，来快速推动问题的解决。
不知道作者是否考虑？

**Comment by langhuihui** [comment]
可以的
