### ISSUE TITLE
GB28181流接入后，反复出现“未找到ssrc”错误

### ISSUE THREAD

**Issue by lonrown** [langhuihui/monibuca#112]
### GB28181流接入后，总是反复出现“未找到ssrc”错误，然后就断掉连接，重连后再出出现该问题，
用的是小厂家的设备

**以下是日志：**
09:31:17	INFO	GB28181	invite response	{"id": "11010000401327000004", "channel": "11010000401327060004", "status code": 200}
09:31:17	INFO	已创建	{"流": "11010000401327000004/11010000401327060004", "id": 669}
09:31:17	INFO	发布	{"流": "11010000401327000004/11010000401327060004", "id": 669, "类型": "PSPublisher", "ptr": "0xc001f4fd60"}
09:31:17	INFO	⌛->🟡	{"流": "11010000401327000004/11010000401327060004", "id": 669, "动作": "publish"}
09:31:17	INFO	订阅	{"流": "11010000401327000004/11010000401327060004", "id": 669, "类型": "FLVRecorder", "ID": "11010000401327000004/11010000401327060004/flv"}
09:31:17	INFO	订阅者+1	{"流": "11010000401327000004/11010000401327060004", "id": 669, "类型": "FLVRecorder", "ID": "11010000401327000004/11010000401327060004/flv", "remains": 1}
09:31:22	WARN	no tracks	{"流": "11010000401327000004/11010000401327060004", "id": 669}
09:31:22	INFO	🟡->🔴	{"流": "11010000401327000004/11010000401327060004", "id": 669, "动作": "timeout"}
09:31:22	INFO	close	{"流": "11010000401327000004/11010000401327060004", "id": 669, "类型": "FLVRecorder", "ID": "11010000401327000004/11010000401327060004/flv", "event": "close"}
09:31:22	INFO	close	{"流": "11010000401327000004/11010000401327060004", "id": 669, "类型": "PSPublisher", "event": "close"}
09:31:22	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:22	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:22	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:22	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}
09:31:23	ERROR	PS	未找到ssrc	{"ssrc": 200008193}

**Comment by langhuihui** [comment]
这个应该是发送的 ssrc 和协商的不一致导致的，你确认一下媒体端口是范围端口吗？

**Comment by lonrown** [comment]
媒体端口现在就用了58200，您指的是这个端口吗？
海康的是正常的

**Comment by gzncland** [comment]
我也出现这个问题，摄像机是海康的。端口范围udp:58200-59200

**Comment by langhuihui** [comment]
可以配置成范围端口，比如58200-59200
