### ISSUE TITLE
如何降低分辨率？

### ISSUE THREAD

**Issue by hessonsu** [langhuihui/monibuca#114]
监控摄像头配置了4K分辨率。使用GB28181推流到M7S。
手机使用webrtc通过公网查看另一个局域网的监控。
此时我希望降低分辨率，从而节省带宽流量
目前所知道的是。
通过ffmpeg 拉流降低分辨率，再重新推流到M7S？
有无更好的办法呢？

**Comment by langhuihui** [comment]
动态调整分辨率，需要用到转码插件，你可以先加我微信 yigehui
