### ISSUE TITLE
请教一下是否有monibuca的压测数据

### ISSUE THREAD

**Issue by Johonnyr** [langhuihui/monibuca#115]
大佬请教一下是否有monibuca的压测数据，目前有项目大概有4k+的摄像头，大部分接在nvr下，局域网网络下使用观看。我们想使用monibuca接入，但在官网下未找到相关的压测数据，不知道我们要满足项目需求应该使用什么样的硬件配置呢

**Comment by langhuihui** [comment]
monibuca 性能和 zlm 差不多，可以参考这篇文章：[内存复用](https://mp.weixin.qq.com/s?__biz=MzkyMDQ5Nzg5MQ==&mid=2247483819&idx=1&sn=188dee78a12ca3d0f28196b2b641519a&chksm=c190ba27f6e73331348848eb84e213b2d49d2e4030bc074c4ea3af7c890f12b0d05f469cf597&scene=178&cur_album_id=2979318380627460104#rd)  你可以配置 invitemode: 2 按需拉流，具体文档：[GB28181](https://monibuca.com/guide/plugins/gb28181.html#%E6%8F%92%E4%BB%B6%E5%BC%95%E5%85%A5)
