### ISSUE TITLE
推 rtmp 到 m7s，長時間放置後會出現 error，同時視頻會出現延遲

### ISSUE THREAD

**Issue by TommyLeng** [langhuihui/monibuca#116]
<img width="1159" alt="image" src="https://github.com/langhuihui/monibuca/assets/95701513/ce8b1120-5195-44d3-9fb4-5a84f9f5c61d">
<img width="1161" alt="image" src="https://github.com/langhuihui/monibuca/assets/95701513/5def677e-6de2-407b-982e-816db437d5b9">
<img width="1365" alt="image" src="https://github.com/langhuihui/monibuca/assets/95701513/b56d0bcb-5e87-463e-b7eb-77026c75906c">

**Comment by langhuihui** [comment]
完整日志有吗？
