### ISSUE TITLE
请教如何在使用API拉流时完全修改拉流的save模式

### ISSUE THREAD

**Issue by Johonnyr** [langhuihui/monibuca#117]
大佬在使用monibuca的拉流过程中发现，save的pullonstart和pullonsub是保存在配置文件内的，如果操作一个流修改save，发现在配置文件内两种模式都存在，如何完全修改拉流的save模式呢

**Comment by langhuihui** [comment]
确实考虑不周，看来最好得用数据库了

**Comment by Johonnyr** [comment]
好的，那我明白了。这个问题是我们想知道在非播放状态下知道某个流的在离线状态，但是又不想一直拉取流时发现的。那请问当前我们的这个想法有办法解决吗

**Comment by Johonnyr** [comment]
目前考虑的做法是：定时去拉取流，通过回调的close事件来判定流离线，对于在线的流过几秒再调用api来关闭。
如果有录制的需求，先把流打开，再调用录制的API，最后再关闭流
感觉略微繁琐，是否有更好的解法呢

**Comment by langhuihui** [comment]
可以通过 api/summary 获取流列表

**Comment by Johonnyr** [comment]
这个和api/list/pull 获取的数据有什么不一样吗

**Comment by langhuihui** [comment]
api/list/pull 罗列的是从远端正在拉流的列表， api/summary罗列的是所有的流

**Comment by Johonnyr** [comment]
好的。另外有一个疑问，当save为2时，如果直接使用record接口录制，停止录制后，流会一直在pull的状态，按照个人理解，如果pullonsub，应该是停止录制后不再拉流了吧

**Comment by langhuihui** [comment]
录制属于内部订阅者，不参与自动停止的判断逻辑

**Comment by Johonnyr** [comment]
那如果想录制后不再拉流的话，是否是只能调用closestream来关闭了呢？这样如果同时在观看的话，观看端会受影响吧，或者此内部订阅在停止录制后是否可以通过某种方法取消呢

**Comment by langhuihui** [comment]
你可以配置录制的 subscribe 的 internal 为 false 就变成非内部订阅者了
