### ISSUE TITLE
不停使用錄影 api 會引致 視頻延遲增加

### ISSUE THREAD

**Issue by TommyLeng** [langhuihui/monibuca#119]
我在公司 有一個攝影機，同時推流去 m7s, srs
一直以來 m7s 延遲都是低一點點

但我業務需求，每分鐘需要 錄影 10秒的 影片
我用了 plugin-recording 的 api 錄影, 錄影格式是 mp4，然後儲在 aws s3

過一晚後 m7s 的視頻延遲會增加，比 srs 多了幾秒
在過多一晚又會增加幾秒

是不是因為錄影 api 用了 "PlayBlock 阻塞式读取数据" 呢？

**Comment by langhuihui** [comment]
如果不开录制的话，不会增加？

**Comment by TommyLeng** [comment]
在不開錄影的情況下，是看不到會有增加延遲，我試了2，3天都沒問題

另外我用的是 m7s docker，用latest 的 build，m7s 大慨是上星期建的

**Comment by langhuihui** [comment]
你试试换一个格式，录制 flv 格式试试呢

**Comment by TommyLeng** [comment]
<img width="1253" alt="image" src="https://github.com/langhuihui/monibuca/assets/95701513/04287862-074c-46ac-8a66-756c2b5adbd4">

這是當時的 log

好的，我剛剛轉了 flv 試試，再觀察一兩天看看

**Comment by TommyLeng** [comment]
轉了 flv 還是一樣

另外 最後我把錄影 api 都停了，發現延遲都會增加
看來和錄影沒有關係，現在不肯定是那裡的問題了

**Comment by langhuihui** [comment]
可以尝试下面的办法，使用最新的 beta 版，设置 subscribe 的 syncmode: 1 ，设置 publish 的 speedlimit: 0
