### ISSUE TITLE
RTSP 拉流中断

### ISSUE THREAD

**Issue by nicklin99** [langhuihui/monibuca#121]
错误日志: "error": "TCP timeout"
有没有设置可以失败后自动重新拉取

**Comment by langhuihui** [comment]
有的，配置 repull

**Comment by nicklin99** [comment]
这个有配置,错误日志的时间线是这样的
"error": "TCP timeout"
dial <ip> operation was canceled"
"error": "terminated"
看日志感觉没生效

**Comment by langhuihui** [comment]
嗯，这种情况估计无法出发重连

**Comment by langhuihui** [comment]
重连机制需要首次连接成功
