### ISSUE TITLE
电视台的 台标功能

### ISSUE THREAD

**Issue by wells1013** [langhuihui/monibuca#124]
可不可以添加 类似电视台的 台标功能呢？用户拉流的时候始终在屏幕的右上角或者 左上角 出现一个 png 的 图片。

**Comment by langhuihui** [comment]
1、直接在前端加，2、服务器加，需要将视频帧解码成图像，再执行图像操作，然后再编码成视频，这个过程非常消耗 CPU，也可以用 GPU 加速，但是也比较消耗资源，而且会增加延迟。
