### ISSUE TITLE
截图用不了

### ISSUE THREAD

**Issue by linfx** [langhuihui/monibuca#129]
snap/34020000001320000001/34020000001320000001
返回0字节

**Comment by langhuihui** [comment]
有日志吗？

**Comment by linfx** [comment]
monibuca_1  | 06:07:10.598Z	INFO	subscribe	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585"}
monibuca_1  | 06:07:10.598Z	INFO	track+1	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "name": "h264"}
monibuca_1  | 06:07:10.598Z	INFO	innersuber +1	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "remains": 1}
monibuca_1  | 06:07:10.598Z	INFO	playblock	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "subType": 0}
monibuca_1  | 06:07:10.598Z	INFO	start read	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "track": "h264", "mode": 0}
monibuca_1  | 06:07:10.598Z	INFO	first frame read	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "track": "h264", "firstTs": "4m45.602720104s", "firstSeq": 7062}
monibuca_1  | 06:07:10.598Z	INFO	close	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "reason": "snap"}
monibuca_1  | 06:07:10.599Z	INFO	play stop	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "type": "SnapSubscriber", "ID": "10.0.0.184:59585", "error": "context canceled"}
monibuca_1  | 06:07:12.113Z	INFO	innersuber -1	{"stream": "34020000001320000001/34020000001320000001", "id": 2, "remains": 0}

**Comment by langhuihui** [comment]
测试过了，没问题
