### ISSUE TITLE
最新Google,流列表播放操作,无法播放视频

### ISSUE THREAD

**Issue by jcshusheng** [langhuihui/monibuca#13]
流列表播放操作，无法播放视频
谷歌浏览器控制台，输出异常：Uncaught ReferenceError: SharedArrayBuffer is not defined
谷歌相关文档：https://developer.chrome.com/blog/enabling-shared-array-buffer/
测试环境:
Google 版本：92.0.4515.107（正式版本） （64 位）
starting m7s  v3.2.2

**Comment by bosscheng** [comment]
@authoritiesw 已经修复了
