### ISSUE TITLE
请问视频播放的连接有没有类似海康30分钟失效的功能

### ISSUE THREAD

**Issue by MetSystem** [langhuihui/monibuca#137]

**Comment by langhuihui** [comment]
30 分钟失效是指，30 分钟无人观看后失效，还是 30 分钟强制失效？

**Comment by MetSystem** [comment]
强制失效，类似鉴权。防止视频连接被扩散产生安全问题。

**Comment by langhuihui** [comment]
那就是鉴权功能，这个可以看文档，鉴权那篇

**Comment by MetSystem** [comment]
应该是连接一直播放是有效，如果30分钟后用同样的连接播放会提示无效
例如 ws://1111/2222?s=abcdef
如果一直播放，该地址一直有效
如果30分钟内重复播放该地址有效
如果超出30分钟，再去请求地址提示连接无效
