### ISSUE TITLE
接口：/api/summary在pullonsub时不返回Streams信息

### ISSUE THREAD

**Issue by Johonnyr** [langhuihui/monibuca#139]
![image](https://github.com/user-attachments/assets/e786ad11-d30b-4697-9770-2920180c0b80)
![image](https://github.com/user-attachments/assets/9c64ec04-b873-4455-8231-260851cb08f9)
最新的版本，如果对流设置了pullonsub，如果流不播放的话，一直获取不到流相关的信息了

**Comment by langhuihui** [comment]
pullonsub 就是只有在订阅时才会拉流啊

**Comment by Johonnyr** [comment]
> pullonsub 就是只有在订阅时才会拉流啊

1. 我们想只在观看时拉取流，节省资源，所以设置了pullonsub；2.同时想知道当前的流状态（在离线），例如设备网络断了、断电，这个时候应该是无法播放了。请教下大佬这两点是否是相悖的

**Comment by langhuihui** [comment]
我理解你的意思，问题是我不去拉流，又如何能获取到你的设备的状态呢？

**Comment by Johonnyr** [comment]
> 我理解你的意思，问题是我不去拉流，又如何能获取到你的设备的状态呢？

明白。我在想是否会有一种定时机制来检测流状态，不过这样做其实业务侧定时去做也可以了
