### ISSUE TITLE
rtmp推流，webrtc拉流播放没有声音

### ISSUE THREAD

**Issue by rh-08** [langhuihui/monibuca#18]
跟踪了一下代码，rtmp推流使用的是aac声音格式，而webrtc使用的格式是pcma或者pcmu，导致webrtc播放端没有声音。
请问如何解决这个问题呢？

**Comment by langhuihui** [comment]
这个需要在服务器进行转码，目前正在研制

**Comment by rh-08** [comment]
找了一下aac转pcm的纯go的源码库，没有找到。写一个转码plugin，还是很厉害的，期待大神佳作。
