### ISSUE TITLE
接口文档

### ISSUE THREAD

**Issue by CNshwfz01a** [langhuihui/monibuca#19]
码神，咱们那个文档上面的http接口是全的吗 那个demo上面获取设备还有分屏的那个页面有没有接口捏~

**Comment by langhuihui** [comment]
/api/gb28181/list 接口里面会定时推送数据出来

**Comment by CNshwfz01a** [comment]
> /api/gb28181/list 接口里面会定时推送数据出来

一直是null

**Comment by langhuihui** [comment]
这个接口目前是SSE（server-sent Event)的，前端需要用EventStream对象来接收，后面我会加上一个参数来改变输出的类型

**Comment by lshsuper** [comment]
embed这个包没有，是怎么回事那？？

**Comment by langhuihui** [comment]
需要go1.16以上版本
