### ISSUE TITLE
用ffmpeg推流，只推mp3不能播放

### ISSUE THREAD

**Issue by ljwps** [langhuihui/monibuca#21]
推流命令如下
ffmpeg -re -stream_loop -1 -i i:/我的/Desktop/a.mp3 -acodec aac -f flv rtmp://127.0.0.1:1935/live/123456

结果：
无ts文件生成，后台流列表可以看到，但点击播放不能播放

**Comment by langhuihui** [comment]
需要配置文件里面将EnableVideo =false
