### ISSUE TITLE
monibuca 播放裸H264

### ISSUE THREAD

**Issue by lsd908321** [langhuihui/monibuca#22]
我有一个xxx.h264文件，我如何将使用http-flv播放，也就是
stream = &engine.Stream{Type: "H264", StreamPath: streamPath}
然后接下去怎么写

**Comment by langhuihui** [comment]
```
if file, err := os.Open(h264path); err == nil {
		stream := Stream{
			Type:       "H264",
			StreamPath: streamPath,
		}
		if stream.Publish() {
			defer stream.Close()
			var lastTime uint32
			//at := stream.NewAudioTrack(0)
			vt := stream.NewVideoTrack(0)
			for {
// 读取文件中单个NALU
				vt.PushNalu(lastTime,0,nalu)
lastTime+=40
time.Sleep(time.Duration(40) * time.Millisecond)
			}
		} else {
			return errors.New("Bad Name")
		}
	} else {
		return err
	}
```

**Comment by lsd908321** [comment]
`
func PublishH264File(streamPath string) error {
	flvPath := streamPath + ".h264"
	os.MkdirAll(filepath.Dir(flvPath), 0755)
	if file, err := os.Open(flvPath); err == nil {
		stream := engine.Stream{
			Type:       "H264File",
			StreamPath: streamPath,
		}
		if stream.Publish() {
			defer stream.Close()
			file.Seek(int64(len(codec.FLVHeader)), io.SeekStart)
			// at := stream.NewAudioTrack(0)
			payload, err := ioutil.ReadAll(file)
			if err != nil {
				return err
			}
			var lastTime uint32
			vt := stream.NewVideoTrack(codec.CodecID_H264)
			for _, nalu := range codec.SplitH264(payload) {
				// 读取文件中单个NALU
				lastTime += 40
				vt.PushNalu(lastTime, 0, nalu)
				time.Sleep(time.Duration(40) * time.Millisecond)
			}
		} else {
			return errors.New("Bad Name")
		}
	} else {
		return err
	}
	return nil
}
`
