### ISSUE TITLE
rtmp 推流到 monibuca，播放对应 hls 时画面花屏

### ISSUE THREAD

**Issue by universix** [langhuihui/monibuca#24]
1. 启动 monibuca 服务程序（v3.4.1，v3.4.3，linux 版本和 windows 版本都试过）
2. 用以下命令推流到服务程序
ffmpeg.exe -i http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8 -c:v copy -an -f flv rtmp://127.0.0.1/live/test110
3. ffplay.exe -i rtmp://127.0.0.1/live/test110 （播放正常）
4. ffplay.exe -i rtmp://127.0.0.1:8080/hls/live/test110.m3u8 （播放时画面花屏，卡顿）
换漳浦的 hls 同样流程推流测试，播放对应 hls 时，非常卡顿

**Comment by langhuihui** [comment]
我用ffplay 直接播放原始的流，也报了很多时间戳的错误，这就会导致问题

**Comment by universix** [comment]
的确有时间戳的错误，可是实际项目中，会比较多遇到类似的输入流，做项目时，只能希望服务程序尽可能去兼容和容错，至少这个流 ffplay 是可以正常播放的

**Comment by langhuihui** [comment]
最新版本已经解决
