### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by universix** [langhuihui/monibuca#25]
monibuca 视频服务开发框架真的非常优秀，非常切合开发的需求，基础视频处理的内核，加上可插拔的网络协议插件，的确可以适应更多的场景，极大的降低开发的难度，以下是个人的几个建议：
1. 明确区分网络协议的Push, Pull, Pub, Sub方法，方便开发调用
这里我借鉴了 [lal手册中](https://pengrl.com/lal/#/Session?id=%e8%bf%9e%e6%8e%a5%e5%bb%ba%e7%ab%8b%e6%96%b9%e5%90%91%e8%a7%92%e5%ba%a6%ef%bc%8cclientsession-serversession) 的定义
例如，有些项目需要 rtmp 推拉，hls 拉，http-ts 拉进行视频流的输入，但只需要 hls 拉，http-ts 拉的输出，不需要 rtmp 拉的输出，二次开发时只需调用对应协议的对应方法。
毕竟 monibuca 架构足够灵活，明确输入和输出的推拿，可以让架构更清晰。
2. 输入断流或卡顿时，可以选择循环现有 RingBuffer 中的视频数据输出
现实场景中，因为网络或者源的问题，有些视频的输入是不稳定的，即使有缓存，视频输出也可能会出现卡顿。RingBuffer 的设计的确非常贴合，完全可以更充分的使用 RingBuffer 中的数据，当源输入不足时，先用 RingBuffer 中已有的视频数据输出，虽然内容不衔接，但视频流的输出可以不中断，用户播放体验会好于卡顿，同时发送事件给后台服务器，提醒运维检查。
3. 希望能控制缓存的长度，缓解输入源的不稳定造成的卡顿
希望能控制缓存的长度，这样当http-flv，http-ts，rtmp输出时，有更大的服务器缓存内容，用空间换时间，在大内存的机器上，可以较好的降低卡顿。
4. 输出 hls 的 m3u8 可以选择动态生成
我的理解，hls 的 m3u8 类似于动态网站的 index.php，当请求 m3u8 时，动态生成内容返回即可。
在有些场景中，例如硬盘 io 较弱但内存较大的机器上，直播视频服务往往希望能不落盘就不落盘，尽量降低硬盘 io，此场景中的视频服务，在内存中做好视频流的归集缓存后，由内存通过网络直接输出，即可以降低延迟，又可以减少瓶颈。

**Comment by langhuihui** [comment]
第四点已经实现了

**Comment by universix** [comment]
> 第四点已经实现了

看了文档，在v3.4.1版中
EnableWrite = false
EnableMemory = true
如上设置后推流，resource/live 目录下，还是有 m3u8 文件生成，而且在不断刷新，也有对应的目录，不过目录中没有文件

**Comment by langhuihui** [comment]
新版的话刷新的m3u8不再写文件了，只保留在内存中
