### ISSUE TITLE
rtsp拉流转发花屏

### ISSUE THREAD

**Issue by wangxin3924** [langhuihui/monibuca#29]
您好，我这遇到几个疑问：
1.请问rtsp拉流转发后，使用ffmpeg命令行录取5秒视频，视频前两秒花屏，播放的时候也是这样的，我看之前有人提过rtmp花屏的问题，请问这些花屏都是一个问题导致的么，能解决么；在x86平台还好，但是arm平台上花屏比较严重.
2.界面切换的时候有的时候需要缓冲好久，这个是我启动的配置文件问题么还是本身就是这样的
3.网络断了有重连机制么
因为我不是做go语言开发的，所以没有深入研究代码，请见谅

**Comment by langhuihui** [comment]
有重连机制的 ，花屏的原因比较复杂，需要具体问题具体分析
