### ISSUE TITLE
RTMP 推流BUG

### ISSUE THREAD

**Issue by kency** [langhuihui/monibuca#31]
只要一有流推进来就闪退 win10 21H2 /64 位
日志：

panic: interface conversion: interface {} is string, not float64

goroutine 31 [running]:
github.com/Monibuca/plugin-rtmp/v3.(*NetConnection).OnConnect(0xc0000fe0e0, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/!monibuca/plugin-rtmp/v3@v3.0.1/netConnection.go:103 +0x58d
github.com/Monibuca/plugin-rtmp/v3.processRtmp(0x18844c0, 0xc000146138)
	C:/Users/runneradmin/go/pkg/mod/github.com/!monibuca/plugin-rtmp/v3@v3.0.1/netStream.go:44 +0x379
created by github.com/Monibuca/utils/v3.ListenTCP
	C:/Users/runneradmin/go/pkg/mod/github.com/!monibuca/utils/v3@v3.0.5/main.go:59 +0x2f4

**Comment by langhuihui** [comment]
我想了解一下这个是用的什么推流工具，可否抓个包呢

**Comment by kency** [comment]
IOS版的，叫 “易推流”，推手机摄像头的实时。但推到我red5服务器就可以推，推这个就闪退
用电脑OBS推就俩服务器都正常。
下载试一下吧

**Comment by langhuihui** [comment]
嗯，我看了一下错误日志，应该是connect命令里面的一个参数解析问题，可否用wireshark抓个包呢

**Comment by kency** [comment]
最新的还没解决？
抓了包发你QQ邮箱了

**Comment by langhuihui** [comment]
这个已经找到问题了，已经修复了

**Comment by kency** [comment]
NICE

_______________________________________________________________________
Roy Liang

发件人: ***@***.***>
发送时间: 2022年4月10日 10:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [langhuihui/monibuca] RTMP 推流BUG (Issue #31)


这个已经找到问题了，已经修复了

―
