### ISSUE TITLE
obs 推流解析错误, 路径最后面出现多余斜杆内容

### ISSUE THREAD

**Issue by lly-ke** [langhuihui/monibuca#32]
- 环境
obs: 27.2-rc1(62位)
monibuca: 最新版本3.2.2

- 问题
默认配置启动m7s, obs软件推rtmp 流解析路径多了个反斜杠, 导致flv m3u8路径播放不了

- 截图
![image](https://user-images.githubusercontent.com/28623614/155473594-866f9bc5-bf75-4db7-bf97-a621f1fc55d4.png)
![image](https://user-images.githubusercontent.com/28623614/155473742-55ff421c-c21c-4501-8798-6da1cfecf4a0.png)
![image](https://user-images.githubusercontent.com/28623614/155473900-8d11b3a8-fcc2-4b56-80b5-9ec882be4dde.png)
![image](https://user-images.githubusercontent.com/28623614/155474087-151258fd-33c6-4fea-8401-57ebdc49ccaf.png)

**Comment by langhuihui** [comment]
test应该写在串流秘钥那个输入框里面，上面写rtmp://localhost/live即可

**Comment by 2720851545** [comment]
可以了, 请问这是什么原因导致的?
