### ISSUE TITLE
/api/gb28181/list缺少移动侦测的录像

### ISSUE THREAD

**Issue by GeekChengZ** [langhuihui/monibuca#34]
/api/gb28181/list只能查询计划的录像，而特殊的如移动侦测、事件录像是没有的

**Comment by langhuihui** [comment]
嗯，这个需要怎么才能查询到呢

**Comment by GeekChengZ** [comment]
> 嗯，这个需要怎么才能查询到呢

https://github.com/Monibuca/plugin-gb28181/commit/c9709d0e482f7129896680ea2536045c83102d90
