### ISSUE TITLE
关于rtsp推流和延迟问题

### ISSUE THREAD

**Issue by ColorDreams** [langhuihui/monibuca#37]
关于推流问题：RTSP推流失败
推流软件：[小葫芦直播助手](https://zs.xiaohulu.com/live/)、[OBS 27.2.4 WinX64](https://obsproject.com/)
推流日志：
> 2022/04/07 13:43:38 HDL start reuse gateway port
2022/04/07 13:43:38 server rtmp start at:1935
2022/04/07 13:43:38 server gb28181 start at127.0.0.1:5060
2022/04/07 13:43:38 Jessica start reuse gateway port
2022/04/07 13:43:38 server gateway start at :8081:8082
2022/04/07 13:43:38 udp server start listen video port[58200]
2022/04/07 13:44:23 rtsp conn opened
2022/04/07 13:44:23 rtsp conn closed (buffer length exceeds 64)
2022/04/07 13:44:25 rtsp conn opened
2022/04/07 13:44:25 rtsp conn closed (buffer length exceeds 64)

关于延迟问题：
经测试，通过rtmp推流和rtsp转流（VLC创建一个rtsp流，然后使用m7s转流）的延迟差不多。flv和ws延迟在2-3秒左右；WebRTC延迟和hls差不多，6-8秒不等，有时候还会更长。实时性很差，都没办法做到一秒以内。GB28181因为没有现成的设备，所以暂时没测。

按理来说，WebRTC的延迟应该会是最低的，但实际却是WebRTC和hls延迟一样高。总体来说，作为一个开源方案，最低延迟能做到稳定2~3秒，还算不错，但是没办法做到秒内，在一些对实时性有要求的场景不太适用。

**Comment by langhuihui** [comment]
WebRTC延迟应该会非常低的，6-8秒不正常

**Comment by ColorDreams** [comment]
> WebRTC延迟应该会非常低的，6-8秒不正常


我又测了一下，这次是部署在Linux服务器上，WebRTC延迟在1秒内。我本机的配置是AMD R7 4800H，8C16T 16G，服务器的配置是64C128T 64G。按理来说，就算是配置的问题，也不应该。

另外，我想问一下，有支持onvif协议的打算吗？

**Comment by langhuihui** [comment]
有人写过onvif的插件了
