### ISSUE TITLE
转码

### ISSUE THREAD

**Issue by YoshieraHuang** [langhuihui/monibuca#4]
monibuca的engine内部有负责转码的部分吗？还是说转码是完全靠插件来完成？

**Comment by langhuihui** [comment]
engine只负责转发

**Comment by YoshieraHuang** [comment]
那比如我要把rtsp源转码成rtmp源，需要怎么弄呢？

**Comment by langhuihui** [comment]
如果是摄像头作为源，可以使用界面上的拉流转发功能，将摄像头的流拉入monibuca中，如果是主动向monibuca用rtsp推流，可以直接向554端口推，然后就可以用rtmp协议从monibcua拉流出来播放了

**Comment by roc2539** [comment]
> 那比如我要把rtsp源转码成rtmp源，需要怎么弄呢？

现在这个要转码的话要怎么弄？

**Comment by roc2539** [comment]
> > 那比如我要把rtsp源转码成rtmp源，需要怎么弄呢？
> 
> 现在这个要转码的话要怎么弄？

文档哪里有介绍这一块或是怎么操作吗？
