### ISSUE TITLE
rtsp推流，1G的大文件视频播放问题

### ISSUE THREAD

**Issue by noroadzh** [langhuihui/monibuca#43]
发现如果是播放1G大小的视频文件，直接报“播放超时”

请问下各位大虾，这种超大的视频文件monibuca进行推流播放应该怎么设置呢

**Comment by langhuihui** [comment]
详细描述一下，你的操作步骤

**Comment by noroadzh** [comment]
> 

我这边就是直接 通过接口创建streampath，然后直接就用jessibuca 进行拉流播放，很简单的一个使用

**Comment by langhuihui** [comment]
推流命令，拉流地址，是怎样的

**Comment by noroadzh** [comment]
> 

具体的命令没注意，从monibuca的管理网站看是很正常的，如果这个文件几百M都能正常播放

**Comment by langhuihui** [comment]
你这个信息量太少了

**Comment by noroadzh** [comment]
额，本来就很简单的操作，我有点怀疑可能是视频的问题
