### ISSUE TITLE
About Record Plugin

### ISSUE THREAD

**Issue by thunderyan** [langhuihui/monibuca#5]
1) Can you provide a parameter to setup the record file name when call the record API from web console or RAW http(s) request?

2) Can you provide a parameter to setup the record file format .flv or .MP4?

**Comment by langhuihui** [comment]
1.Yes.It's easy.
2.MP4 is not a streaming media format. And a flv file is easy to convert to mp4.

**Comment by thunderyan** [comment]
Noted with thanks. and 1) you will add in future, right?

**Comment by langhuihui** [comment]
It will be done

**Comment by langhuihui** [comment]
mp4 is supported now!
