### ISSUE TITLE
/webrtc/play/ 访问出错？

### ISSUE THREAD

**Issue by creatao** [langhuihui/monibuca#52]
19:44:43        [35mDEBUG[0m  visit   {"plugin": "WebRTC", "path": "/webrtc/play/?streamPath=34020000001320000001/34020000001320000001", "remote": "XXXXXXX:26375"}
2022/06/03 19:44:43 http: panic serving XXXXXXX:26375: runtime error: invalid memory address or nil pointer dereference
goroutine 175 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1825 +0xbf
panic({0x12e1400, 0x1982230})
        D:/Program Files/Go/src/runtime/panic.go:844 +0x258
github.com/pion/webrtc/v3.(*API).NewPeerConnection(0x0, {{0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
        C:/Users/Administrator/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.25/peerconnection.go:134 +0x170
m7s.live/plugin/webrtc/v4.(*WebRTCConfig).Play_(0x1a055c0?, {0x14c05c0, 0xc0000b0000}, 0xc000218100)
        C:/Users/Administrator/go/pkg/mod/m7s.live/plugin/webrtc/v4@v4.0.0-20220512011147-77109592816a/main.go:90 +0x218
m7s.live/engine/v4.(*Plugin).logHandler.func1({0x14c05c0, 0xc0000b0000}, 0xc000218100)
        C:/Users/Administrator/go/pkg/mod/m7s.live/engine/v4@v4.1.2/plugin.go:61 +0x203
net/http.HandlerFunc.ServeHTTP(...)
        D:/Program Files/Go/src/net/http/server.go:2084
m7s.live/engine/v4/util.CORS.func1({0x14c05c0, 0xc0000b0000}, 0xc000218100)
        C:/Users/Administrator/go/pkg/mod/m7s.live/engine/v4@v4.1.2/util/socket.go:78 +0x30d
net/http.HandlerFunc.ServeHTTP(0x226533b3170?, {0x14c05c0?, 0xc0000b0000?}, 0xc0dda5?)
        D:/Program Files/Go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0002b24c2?, {0x14c05c0, 0xc0000b0000}, 0xc000218100)
        D:/Program Files/Go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0003d09c0?}, {0x14c05c0, 0xc0000b0000}, 0xc000218100)
        D:/Program Files/Go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000238000, {0x14c0c68, 0xc00022be30})
        D:/Program Files/Go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        D:/Program Files/Go/src/net/http/server.go:3071 +0x4db

请问该如何解决？

**Comment by langhuihui** [comment]
调用地址不对，应该这么写：/webrtc/play/34020000001320000001/34020000001320000001
