### ISSUE TITLE
webrtc/play/接口收不到answer

### ISSUE THREAD

**Issue by xiongfeigood** [langhuihui/monibuca#53]
发送给接口格式如下：http://10.1.13.15:8081/webrtc/play/11111111111111111112/00000000001320000001，发送offer，收到服务器返回的还是offer，无法建立peer连接。在V3版本上测试是可以的。
请问v4版本还不支持吗，还是我的接口调用有问题呢？
还有请问v4版本的后台管理地址是多少呢？

**Comment by langhuihui** [comment]
你可以通过控制台观察预览插件preview页面中的通讯，选择webrtc方式就能看到了。v4的后台还在开发中。
