### ISSUE TITLE
拉取远程的RTSP流，用RTMP播放 程序意外终止

### ISSUE THREAD

**Issue by Wo-com** [langhuihui/monibuca#56]
10:22:15        INFO   install {"plugin": "HDL", "version": "v4.0.0-202
20520061858-640094798008"}
10:22:15        INFO   install {"plugin": "RTMP", "version": "v4.0.0-20
220526123604-cbe785dedaae"}                                                     
10:22:15        INFO   install {"plugin": "RTSP", "version": "v4.0.0-20
220605130937-f9bc450d0186"}                                                     
10:22:15        INFO   Ⓜ starting m7s v4                       
10:22:15        INFO   http handle added:/api/closestream      {"engine
": true}                                                                        
10:22:15        INFO   http handle added:/api/getconfig        {"engine
": true}                                                                        
10:22:15        INFO   http handle added:/api/modifyconfig     {"engine
": true}                                                                        
10:22:15        INFO   http handle added:/api/plugins  {"engine": true}
                                                                                
10:22:15        INFO   http handle added:/api/stream   {"engine": true}
                                                                                
10:22:15        INFO   http handle added:/api/summary  {"engine": true}
                                                                                
10:22:15        INFO   http handle added:/api/sysinfo  {"engine": true}
                                                                                
10:22:15        INFO   http handle added:/api/updateconfig     {"engine
": true}                                                                        
10:22:15        INFO   http handle added:/     {"engine": true}        
10:22:15        DEBUG          {"config": "global", "config": engine:  
    publish:                                                                    
        pubaudio: true                                                          
        pubvideo: true                                                          
        kickexist: false                                                        
        publishtimeout: 10                                                      
        waitclosetimeout: 0                                                     
    subscribe:                                                                  
        subaudio: true                                                          
        subvideo: true                                                          
        iframeonly: false                                                       
        waittimeout: 10                                                         
    http:                                                                       
        listenaddr: :8080                                                       
        listenaddrtls: ""                                                       
        certfile: ""                                                            
        keyfile: ""                                                             
        cors: true                                                              
        username: ""                                                            
        password: ""                                                            
    rtpreorder: false                                                           
    enableavcc: true                                                            
    enablertp: true                                                             
    enableflv: true                                                             
    consoleurl: wss://console.monibuca.com/ws/v1                                
    secret: ""}                                                                 
10:22:15        INFO   http handle added:/api/list     {"plugin": "HDL"
}                                                                               
10:22:15        INFO   http handle added to engine:/hdl/api/list       
        {"plugin": "HDL"}                                                       
10:22:15        INFO   �🌐 http listen at :8080               
10:22:15        INFO   http handle added:/api/pull     {"plugin": "HDL"
}                                                                               
10:22:15        INFO   http handle added to engine:/hdl/api/pull       
        {"plugin": "HDL"}                                                       
10:22:15        INFO   http handle added:/     {"plugin": "HDL"}       
10:22:15        INFO   http handle added to engine:/hdl/       {"plugin
": "HDL"}                                                                       
10:22:15        DEBUG  config  {"plugin": "HDL", "config": http:       
    listenaddr: :8080                                                           
    listenaddrtls: ""                                                           
    certfile: ""                                                                
    keyfile: ""                                                                 
    cors: true                                                                  
    username: ""                                                                
    password: ""                                                                
publish:                                                                        
    pubaudio: true                                                              
    pubvideo: true                                                              
    kickexist: false                                                            
    publishtimeout: 10                                                          
    waitclosetimeout: 0                                                         
subscribe:                                                                      
    subaudio: true                                                              
    subvideo: true                                                              
    iframeonly: false                                                           
    waittimeout: 10                                                             
pull:                                                                           
    repull: 0                                                                   
    pullonstart: false                                                          
    pullonsubscribe: false                                                      
    pulllist: {}}                                                               
10:22:15        DEBUG  config  {"plugin": "RTMP", "config": publish:            
    pubaudio: true                                                              
    pubvideo: true                                                              
    kickexist: false                                                            
    publishtimeout: 10                                                          
    waitclosetimeout: 0                                                         
subscribe:                                                                      
    subaudio: true                                                              
    subvideo: true                                                              
    iframeonly: false                                                           
    waittimeout: 10                                                             
tcp:                                                                            
    listenaddr: :1935                                                           
    listennum: 0                                                                
pull:                                                                           
    repull: 0                                                                   
    pullonstart: false                                                          
    pullonsubscribe: false                                                      
    pulllist: {}                                                                
push:                                                                           
    repush: 0                                                                   
    pushlist: {}                                                                
chunksize: 4096                                                                 
keepalive: false}                                                               
10:22:15        INFO   server rtmp start at    {"plugin": "RTMP", "list
en addr": ":1935"}                                                              
10:22:15        INFO   http handle added to engine:/rtsp/api/pull      
        {"plugin": "RTSP"}                                                      
10:22:15        INFO   http handle added to engine:/rtsp/api/push      
        {"plugin": "RTSP"}                                                      
10:22:15        INFO   http handle added to engine:/rtsp/api/list      
        {"plugin": "RTSP"}                                                      
10:22:15        DEBUG  config  {"plugin": "RTSP", "config": publish:   
    pubaudio: true                                                              
    pubvideo: true                                                              
    kickexist: false                                                            
    publishtimeout: 10                                                          
    waitclosetimeout: 0                                                         
subscribe:                                                                      
    subaudio: true                                                              
    subvideo: true                                                              
    iframeonly: false                                                           
    waittimeout: 10                                                             
    waittimeout: 10
pull:
    repull: 0
    pullonstart: true
    pullonsubscribe: false
    pulllist:
        live/test: rtsp://admin:gqgs@123@153.66.173.204:554/ch1/main/av_stream
push:
    repush: 0
    pushlist: {}
listenaddr: :554
udpaddr: :8000
rtcpaddr: :8001
readbuffersize: 2048
map: {}}
10:22:15        INFO   pull    {"plugin": "RTSP", "path": "live/test", "url": "rtsp://admin:gqgs@123@153.66.173.204:554/ch1/main/av_stream"}
10:22:15        INFO   publish {"plugin": "RTSP", "path": "live/test"}
10:22:15        INFO   created {"stream": "live/test"}
10:22:15        DEBUG  ⌛->🟢 {"stream": "live/test", "action"
: "publish"}
10:22:15        INFO   track +1        {"stream": "live/test", "name": "pcma"}
10:22:15        INFO   track +1        {"stream": "live/test", "name": "h264"}
10:22:15        DEBUG  resize(256→6)   {"stream": "live/test", "name": "h264"}
10:22:23        DEBUG  recv cmd        {"plugin": "RTMP", "commandName": "connect", "streamID": 0}
10:22:23        INFO   connect {"plugin": "RTMP", "appName": "live", "objectEncoding": 0}
10:22:23        DEBUG  recv cmd        {"plugin": "RTMP", "commandName": "createStream", "streamID": 0}                                                                                       
10:22:23        INFO   createStream:   {"plugin": "RTMP", "streamId": 1}                                                                                                                      
10:22:23        INFO   decode command amf0     {"plugin": "RTMP", "cmd": "getStreamLength"}                                                                                                   
10:22:23        DEBUG  recv cmd        {"plugin": "RTMP", "commandName": "play", "streamID": 1}                                                                                               
10:22:23        INFO   subscribe       {"plugin": "RTMP", "path": "live/test"}                                                                                                                
10:22:23        DEBUG  Stream Found    {"stream": "live/test"}                                                                                                                                
10:22:23        INFO   suber +1        {"stream": "live/test", "id": "[::1]:21206|1", "type": "RTMP", "remains": 1}                                                                           
10:22:23        INFO   track+1 {"stream": "live/test", "type": "RTMP", "ID": "[::1]:21206|1", "name": "pcma"}                                                                                 
10:22:23        INFO   track+1 {"stream": "live/test", "type": "RTMP", "ID": "[::1]:21206|1", "name": "h264"}                                                                                 
10:22:23        DEBUG  wrong action    {"stream": "live/test", "action": "first enter"}                                                                                                       
10:22:23        INFO   playblock       {"stream": "live/test", "type": "RTMP", "ID": "[::1]:21206|1"}                                                                                         
10:22:23        DEBUG  firstIFrame     {"stream": "live/test", "type": "RTMP", "ID": "[::1]:21206|1", "seq": 186}
10:22:23        DEBUG  skip to latest key frame        {"stream": "live/test", "type": "RTMP", "ID": "[::1]:21206|1", "seq": 187}
10:22:23        INFO   stop    {"stream": "live/test", "type": "RTMP", "ID": "[::1]:21206|1"}                                                                                                 

Process finished with the exit code 2

**Comment by langhuihui** [comment]
看一下是否有fatal.log文件

**Comment by myahuang** [comment]
我用rtsp拉流到m7s，然后在vlc播放器里用rtmp格式播放，播放不了，用rtsp播放延时3秒，用flv格式播放延时8秒

**Comment by langhuihui** [comment]
用最新版本测试一下
