### ISSUE TITLE
订阅一个不存在的rtsp流（rtsp://localhost/live/test），会报这样一个错误

### ISSUE THREAD

**Issue by yuanshengpan** [langhuihui/monibuca#57]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x79a5cf]

goroutine 46 [running]:
github.com/aler9/gortsplib.(*ServerConn).handleRequest(0xc000cf04e0, 0xc000d18180)
	/home/runner/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220606105133-0101ad961ccd/serverconn.go:456 +0xd8f
github.com/aler9/gortsplib.(*ServerConn).handleRequestOuter(0xc000cf04e0, 0xc000d18180)
	/home/runner/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220606105133-0101ad961ccd/serverconn.go:574 +0x85
github.com/aler9/gortsplib.(*ServerConn).runInner(0xc000cf04e0, 0xc00013a180, 0xc00013a1e0)
	/home/runner/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220606105133-0101ad961ccd/serverconn.go:151 +0x18d
github.com/aler9/gortsplib.(*ServerConn).run(0xc000cf04e0)
	/home/runner/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220606105133-0101ad961ccd/serverconn.go:120 +0x3a5
created by github.com/aler9/gortsplib.newServerConn
	/home/runner/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220606105133-0101ad961ccd/serverconn.go:79 +0x325

**Comment by langhuihui** [comment]
已经给github.com/aler9/gortsplib 提PR了，但是一直没有被合入

**Comment by langhuihui** [comment]
已经和作者沟通，我这边来处理，不存在的流我要返回一个404
