### ISSUE TITLE
hook 配置的问题

### ISSUE THREAD

**Issue by amwu** [langhuihui/monibuca#69]
一、当仅配置 urllist 时，出现 requestlist 没有初始化为 nil 的 panic。
二、当同时配置 urllist 和 requestlist 时，出现 reflect.Value.Convert() panic

[https://github.com/Monibuca/plugin-hook/issues/1](https://github.com/Monibuca/plugin-hook/issues/1)

**Comment by langhuihui** [comment]
解决了https://github.com/langhuihui/monibuca/commit/96d886c7a5943220ca04408322a3c667accd4ea6
