### ISSUE TITLE
RTMP流延迟优化问题

### ISSUE THREAD

**Issue by hike2008** [langhuihui/monibuca#7]
请问，目前的RTMP插件，试了下，延迟基本在5s左右，如何进行优化能降低此延迟呢

**Comment by langhuihui** [comment]
你怎么测的

**Comment by hike2008** [comment]
本地服务器，obs推，ffplay 拉流
然后在obs端推时间戳，跟ffplay拉流的时间戳进行对比

**Comment by forcemeter** [comment]
我目前测试了 srs (3.5秒)、 nginx-rtmp(3秒)、LiveGo(3秒)、monibuca(6秒)

**Comment by langhuihui** [comment]
之前机制确实有问题，你现在再试试呢

**Comment by langhuihui** [comment]
延迟已优化
