### ISSUE TITLE
转推到CDN会失败

### ISSUE THREAD

**Issue by flying19880517** [langhuihui/monibuca#70]
使用转推功能时，转推URL填CDN地址会直接停止，不同CDN表现还不一致，推到m7s没问题。
网宿的能看到decode command amf0     {"plugin": "RTMP", "cmd": "onBWDone"}，腾讯和B站的都是直接push finished

    18:45:53        INFO    connect {"plugin": "RTMP", "appName": "live", "objectEncoding": 0}
    18:45:53        INFO    createStream:   {"plugin": "RTMP", "streamId": 1}
    18:45:53        INFO    publish {"plugin": "RTMP", "path": "live/rtmp"}
    18:45:53        INFO    created {"stream": "live/rtmp"}
    18:45:53        INFO    ⌛->🟢  {"stream": "live/rtmp", "action": "publish"}
    18:45:53        INFO    push    {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://网宿CDN地址"}
    18:45:53        INFO    track +1        {"stream": "live/rtmp", "name": "aac"}
    18:45:53        INFO    track +1        {"stream": "live/rtmp", "name": "h264"}
    18:45:53        INFO    _result :       {"plugin": "RTMP", "code": "NetConnection.Connect.Success"}
    18:45:53        INFO    connect {"plugin": "RTMP", "remoteURL": "rtmp://网宿CDN地址"}
    18:45:53        INFO    subscribe       {"plugin": "RTMP", "path": "live/rtmp"}
    18:45:53        INFO    suber +1        {"stream": "live/rtmp", "id": "", "type": "RTMPPusher", "remains": 1}
    18:45:53        INFO    track+1 {"stream": "live/rtmp", "type": "RTMPPusher", "name": "aac"}
    18:45:53        INFO    track+1 {"stream": "live/rtmp", "type": "RTMPPusher", "name": "h264"}
    18:45:53        INFO    start push      {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://网宿CDN地址"}
    18:45:53        INFO    subscribe       {"plugin": "HLS", "path": "live/rtmp"}
    18:45:53        INFO    suber +1        {"stream": "live/rtmp", "id": "", "type": "HLSWriter", "remains": 2}
    18:45:53        INFO    track+1 {"stream": "live/rtmp", "type": "HLSWriter", "name": "aac"}
    18:45:53        INFO    track+1 {"stream": "live/rtmp", "type": "HLSWriter", "name": "h264"}
    18:45:53        INFO    decode command amf0     {"plugin": "RTMP", "cmd": "onBWDone"}
    18:45:53        INFO    push finished   {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://网宿CDN地址"}
    18:45:53        INFO    playblock       {"stream": "live/rtmp", "type": "HLSWriter"}
    
    
    
    18:47:22        INFO    connect {"plugin": "RTMP", "appName": "live", "objectEncoding": 0}
    18:47:22        INFO    createStream:   {"plugin": "RTMP", "streamId": 1}
    18:47:22        INFO    publish {"plugin": "RTMP", "path": "live/rtmp"}
    18:47:22        INFO    created {"stream": "live/rtmp"}
    18:47:22        INFO    ⌛->🟢  {"stream": "live/rtmp", "action": "publish"}
    18:47:22        INFO    push    {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://腾讯CDN地址"}
    18:47:22        INFO    subscribe       {"plugin": "HLS", "path": "live/rtmp"}
    18:47:22        INFO    suber +1        {"stream": "live/rtmp", "id": "", "type": "HLSWriter", "remains": 1}
    18:47:22        INFO    track +1        {"stream": "live/rtmp", "name": "aac"}
    18:47:22        INFO    track+1 {"stream": "live/rtmp", "type": "HLSWriter", "name": "aac"}
    18:47:22        INFO    track +1        {"stream": "live/rtmp", "name": "h264"}
    18:47:22        INFO    track+1 {"stream": "live/rtmp", "type": "HLSWriter", "name": "h264"}
    18:47:22        INFO    playblock       {"stream": "live/rtmp", "type": "HLSWriter"}
    18:47:22        INFO    _result :       {"plugin": "RTMP", "code": "NetConnection.Connect.Success"}
    18:47:22        INFO    connect {"plugin": "RTMP", "remoteURL": "rtmp://腾讯CDN地址"}
    18:47:22        INFO    subscribe       {"plugin": "RTMP", "path": "live/rtmp"}
    18:47:22        INFO    suber +1        {"stream": "live/rtmp", "id": "", "type": "RTMPPusher", "remains": 2}
    18:47:22        INFO    track+1 {"stream": "live/rtmp", "type": "RTMPPusher", "name": "aac"}
    18:47:22        INFO    track+1 {"stream": "live/rtmp", "type": "RTMPPusher", "name": "h264"}
    18:47:22        INFO    start push      {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://腾讯CDN地址"}
    18:47:22        INFO    _result :       {"plugin": "RTMP", "code": "NetStream.Publish.Start"}
    18:47:22        INFO    playblock       {"stream": "live/rtmp", "type": "RTMPPusher"}
    18:47:23        INFO    push finished   {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://腾讯CDN地址"}
    18:47:23        INFO    stop    {"stream": "live/rtmp", "type": "RTMPPusher"}
    18:47:27        INFO    suber -1        {"stream": "live/rtmp", "id": "", "type": "RTMPPusher", "remains": 1}
    
    
    
    18:51:33        INFO    connect {"plugin": "RTMP", "appName": "live", "objectEncoding": 0}
    18:51:33        INFO    createStream:   {"plugin": "RTMP", "streamId": 1}
    18:51:33        INFO    publish {"plugin": "RTMP", "path": "live/rtmp"}
    18:51:33        INFO    created {"stream": "live/rtmp"}
    18:51:33        INFO    ⌛->🟢  {"stream": "live/rtmp", "action": "publish"}
    18:51:33        INFO    push    {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://B站CDN地址"}
    18:51:33        INFO    subscribe       {"plugin": "HLS", "path": "live/rtmp"}
    18:51:33        INFO    suber +1        {"stream": "live/rtmp", "id": "", "type": "HLSWriter", "remains": 1}
    18:51:33        INFO    track +1        {"stream": "live/rtmp", "name": "aac"}
    18:51:33        INFO    track+1 {"stream": "live/rtmp", "type": "HLSWriter", "name": "aac"}
    18:51:33        INFO    track +1        {"stream": "live/rtmp", "name": "h264"}
    18:51:33        INFO    track+1 {"stream": "live/rtmp", "type": "HLSWriter", "name": "h264"}
    18:51:33        INFO    playblock       {"stream": "live/rtmp", "type": "HLSWriter"}
    18:51:33        INFO    _result :       {"plugin": "RTMP", "code": "NetConnection.Connect.Success"}
    18:51:33        INFO    connect {"plugin": "RTMP", "remoteURL": "rtmp://B站CDN地址"}
    18:51:33        INFO    subscribe       {"plugin": "RTMP", "path": "live/rtmp"}
    18:51:33        INFO    suber +1        {"stream": "live/rtmp", "id": "", "type": "RTMPPusher", "remains": 2}
    18:51:33        INFO    track+1 {"stream": "live/rtmp", "type": "RTMPPusher", "name": "aac"}
    18:51:33        INFO    track+1 {"stream": "live/rtmp", "type": "RTMPPusher", "name": "h264"}
    18:51:33        INFO    start push      {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://B站CDN地址"}
    18:51:33        INFO    push finished   {"plugin": "RTMP", "path": "live/rtmp", "url": "rtmp://B站CDN地址"}
    18:51:38        INFO    suber -1        {"stream": "live/rtmp", "id": "", "type": "RTMPPusher", "remains": 1}

**Comment by KEIONG** [comment]
这个问题还有吗 目前

**Comment by langhuihui** [comment]
你试试最新的4.4.0，如果还有问题，我再看

**Comment by flying19880517** [comment]
之前测试的是4.0.7，换成4.4.0后我试了下腾讯CDN地址，不像之前直接退出了，但是还有错误，且拉流观看时卡顿和马赛克严重。我是用ffmpeg推本地文件用rtmp方式推到m7s，然后让m7s转推的，直接用ffmpeg推到cdn上是正常的。

        
        15:59:03        INFO    m7s@v4.4.0 start success
        15:59:06        INFO    connect {"plugin": "RTMP", "appName": "live", "objectEncoding": 0}
        15:59:06        INFO    decode command amf0     {"plugin": "RTMP", "cmd": "FCPublish"}
        15:59:06        INFO    createStream:   {"plugin": "RTMP", "streamId": 1}
        15:59:06        INFO    publish {"plugin": "RTMP", "path": "live/ximalaya"}
        15:59:06        INFO    created {"stream": "live/ximalaya"}
        15:59:06        INFO    ⌛->🟢  {"stream": "live/ximalaya", "action": "publish"}
        15:59:06        INFO    push    {"plugin": "RTMP", "path": "live/ximalaya", "url": "rtmp://腾讯CDN地址"}
        15:59:06        INFO    start push      {"plugin": "RTMP", "path": "live/ximalaya", "url": "rtmp://腾讯CDN地址"}
        15:59:06        INFO    subscribe       {"plugin": "RTMP", "path": "live/ximalaya"}
        15:59:06        INFO    suber +1        {"stream": "live/ximalaya", "type": "RTMPPusher", "remains": 1}
        15:59:06        INFO    track +1        {"stream": "live/ximalaya", "name": "aac"}
        15:59:06        INFO    track+1 {"stream": "live/ximalaya", "type": "RTMPPusher", "name": "aac"}
        15:59:06        INFO    track +1        {"stream": "live/ximalaya", "name": "h264"}
        15:59:06        INFO    track+1 {"stream": "live/ximalaya", "type": "RTMPPusher", "name": "h264"}
        15:59:35        INFO    _result :       {"plugin": "RTMP", "code": "NetConnection.Connect.Success"}
        15:59:35        INFO    connect {"plugin": "RTMP", "remoteURL": "rtmp://腾讯CDN地址"}
        15:59:35        INFO    _result :       {"plugin": "RTMP", "code": "NetStream.Publish.Start"}
        15:59:35        INFO    playblock       {"stream": "live/ximalaya", "type": "RTMPPusher"}
        15:59:54        ERROR   payload is empty        {"stream": "live/ximalaya", "type": "RTMPPusher", "error": "payload is empty"}
        15:59:54        ERROR   payload is empty        {"stream": "live/ximalaya", "type": "RTMPPusher", "error": "payload is empty"}
        16:00:07        ERROR   payload is empty        {"stream": "live/ximalaya", "type": "RTMPPusher", "error": "payload is empty"}
        16:00:07        ERROR   payload is empty        {"stream": "live/ximalaya", "type": "RTMPPusher", "error": "payload is empty"}
        16:00:30        ERROR   payload is empty        {"stream": "live/ximalaya", "type": "RTMPPusher", "error": "payload is empty"}
        16:00:30        ERROR   payload is empty        {"stream": "live/ximalaya", "type": "RTMPPusher", "error": "payload is empty"}

**Comment by langhuihui** [comment]
ffmpeg命令和本地文件发给我，可以加我微信yigehui

**Comment by flying19880517** [comment]
4.4.1验证可以正常推了
