### ISSUE TITLE
rtsp拉流关闭失败

### ISSUE THREAD

**Issue by haowenjiang** [langhuihui/monibuca#71]
通过rtsp拉流到系统中，调用/api/closestream?streamPath=xxx进行关闭，系统显示也是关闭了。但网络抓包发现还一直在rtsp取流中，能否做到关闭的时候也关闭取流

**Comment by haowenjiang** [comment]
拉流开始后就自动有一个HLS的订阅，是默认的吗？

**Comment by haowenjiang** [comment]
21:59:52	INFO	pull	{"plugin": "RTSP", "path": "road/114", "url": "rtsp://xxx:xxx@10.123.21.14"}
21:59:52	INFO	publish	{"plugin": "RTSP", "path": "road/114"}
21:59:52	INFO	created	{"stream": "road/114"}
21:59:52	INFO	⌛->🟢	{"stream": "road/114", "action": "publish"}
21:59:52	INFO	subscribe	{"plugin": "HLS", "path": "road/114"}
21:59:52	INFO	suber +1	{"stream": "road/114", "id": "", "type": "HLSWriter", "remains": 1}
21:59:52	INFO	track +1	{"stream": "road/114", "name": "h264"}
21:59:52	INFO	track+1	{"stream": "road/114", "type": "HLSWriter", "name": "h264"}
22:00:02	INFO	playblock	{"stream": "road/114", "type": "HLSWriter"}
22:00:02	INFO	firstIFrame	{"stream": "road/114", "type": "HLSWriter", "seq": 201}
22:00:25	INFO	🟢->🔴	{"stream": "road/114", "action": "close"}
22:00:25	INFO	stop	{"stream": "road/114", "type": "HLSWriter"}

**Comment by haowenjiang** [comment]
测试拉取http-flv流是可以正常关闭的

**Comment by langhuihui** [comment]
确实有这个问题，我尽快修复一下

**Comment by langhuihui** [comment]
[修复commit](https://github.com/Monibuca/plugin-rtsp/commit/3cbf22576bddf6e0016aeba8ba5b93f19730fa3f)
