### ISSUE TITLE
windows11环境下使用ffmpeg推送mp4至rtmp断开后内存会不断飚升至程序崩溃

### ISSUE THREAD

**Issue by yujie5** [langhuihui/monibuca#75]
命令
ffmpeg -re -i 11-15-02.mp4 -vcodec libx264 -acodec aac -f flv "rtmp://127.0.0.1:1935/live/test"
![image](https://user-images.githubusercontent.com/19257784/220587622-b5c4e957-c810-4f0d-8959-899f5b46a4af.png)
ctrl+C退出。
这时查看cpu，会不断飙升

**Comment by langhuihui** [comment]
m7s端日志呢？

**Comment by yujie5** [comment]
这个是我重新推了个流，不过是推给rtsp的， 一样的问题，都会内存飙升
![image](https://user-images.githubusercontent.com/19257784/220607682-d18299da-a35a-4fbb-bcf5-b7aec6b03517.png)
ffmpeg  -re -i 11-15-02.mp4 -vcodec copy -f rtsp -rtsp_transport tcp  "rtsp://127.0.0.1:554/live/test"    推流命令是这个

**Comment by yujie5** [comment]
我可以提供向日葵，远程调试给您看

**Comment by langhuihui** [comment]
标题是内存飙升，但是你下面又说是cpu飙升，到底是内存还是cpu飙升

**Comment by yujie5** [comment]
哦哦，口误口误，就是内存飙升，内存飙升最后导致程序崩溃

**Comment by langhuihui** [comment]
你用我今天刚发的版本测一下试试

**Comment by yujie5** [comment]
好的，我试试

**Comment by yujie5** [comment]
重新下载的程序正常
