### ISSUE TITLE
近期使用发现了两个问题：声音传输、接收不到流

### ISSUE THREAD

**Issue by lonrown** [langhuihui/monibuca#76]
1. 我回退测试了好几个版本，从4.4.13（该版正常传输音频）版本以后，从摄像头中传输的音频卡顿，几乎听不清楚；
2. 运行一段时间后，会报如下错误，影像无法传输，重启后便OK了：
ERROR	play neither video nor audio	{"stream": "11010000001320000066/11010000001320000066", "type": "JessicaSubscriber", "ID": "202.106.126.229:10081"}

望解决，依然感谢作者及广大贡献者的开源分享，感恩！

**Comment by langhuihui** [comment]
你测的是哪个版本

**Comment by lonrown** [comment]
4.4.17和4.4.18都测试了，声音不正常，一卡一卡的
往前会退到4.4.13版本，声音正常传输，望解决，谢谢啦！
