### ISSUE TITLE
码率超过8M订阅的视频流极容易出现问题

### ISSUE THREAD

**Issue by itqianqiuye** [langhuihui/monibuca#78]
**Monibuca Version: v4.5.2**

**准备数据：**
m7s 保持默认配置，视频为 PR2022 导出。
视频信息：(mask-c20-h264-720p.mp4)
采用 H264 编码，时长 5 分钟，大小 370MB，1280*720，峰值码率可达 12M，使用 ffmpeg 配合 -re 参数，通过 rtsp 协议推流到 m7s。
**推流命令：**
ffmpeg -re -i "mask-c20-h264-720p.mp4" -c copy -f rtsp -rtsp_transport tcp "rtsp://localhost/live/m7s_vf_101"
播放命令：
ffplay -rtsp_transport tcp rtsp://localhost/live/m7s_vf_101 -x 640
ffplay http://localhost:8080/hdl/live/m7s_vf_101.flv -x 640

**复现步骤：**
1、新下载解压，不做任何配置修改，直接启动 m7s.exe
2、打开 cmd 执行上面的推流命令，向 m7s 上推流
3、在浏览器中新建下载 http://localhost:8080/hdl/live/m7s_vf_101.flv，使用 Chrome 浏览器
4、观察下载进度条，正常时下载速度约在 1000KB/s，下载一小会约 30 秒钟，下载速度开始逐渐增加到 30MB/s，正常下载时 cpu 占用很少约 0.1%，出现异常后 cpu 占用增加到 8%，关闭下载任务后，cpu 占用恢复

**复现概率：**
总是可以复现

**视频下载地址：**
[](url)https://pan.baidu.com/s/1XLFH4P-N6-HqEP8ZFWriWA?pwd=wn4p

上传了两个视频，720P 的那个更容易复现问题，480P 的那个码率约 3M，也有一定的机率出现上面的问题。

**Comment by langhuihui** [comment]
加我微信吧yigehui
