### ISSUE TITLE
启动监听的是ipv6

### ISSUE THREAD

**Issue by yangchao2015** [langhuihui/monibuca#8]
![image](https://user-images.githubusercontent.com/11486388/100055716-3f145500-2e5f-11eb-8f4f-68cc1f1408f0.png)
安装完之后 通过 nohup $GOPATH/bin/monibuca > nohup.out & 启动之后，可以正常启动，但是通过lsof -i查看显示，监听的type 是ipv6，如何修改为ipv4

**Comment by langhuihui** [comment]
监听地址里面加上IP试试

**Comment by yangchao2015** [comment]
您好，您的邮件已收到，谢谢！

**Comment by yangchao2015** [comment]
您好，您的邮件已收到，谢谢！
