### ISSUE TITLE
无音频流推流和拉流同时启动，订阅者会等待大约10s才开始传输数据

### ISSUE THREAD

**Issue by haowanxing** [langhuihui/monibuca#81]
如题描述，使用场景是RTMP推流和flv拉流同时启动（先推流后拉流，间隔小于1s），此时如果推流没有音频，则订阅者会等待默认10s才会传输流数据。 这样带来的现象就是从点击播放到出现画面大约延迟10s，而且丢失了前10s的画面。
从日志上看，stream created后立马stream publish了然后subscribe suber +1，发布者发布视频轨道video track attached，订阅者track+1(name: h264)，此后过了约8s，才出现playblock。

日志截图：
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/7816296/235049961-bc76092a-e289-4aef-ba33-5fc1c3eb0127.png">

目前能够解决的方案是将配置文件中的publish.pubaudio设置为false，可以解决AudioTrackWait的阻塞等待问题。但是无法确定会不会导致某些情况致使有音轨的流最后订阅不到音轨导致视频流没有声音。

**Comment by langhuihui** [comment]
rtmp协议无法确定是否包含音频数据，所以订阅者会等待音频轨道
