### ISSUE TITLE
RECORD流录制插件，是否可以自定义流录制文件的名称

### ISSUE THREAD

**Issue by Johonnyr** [langhuihui/monibuca#88]
![image](https://github.com/langhuihui/monibuca/assets/39769813/3c8ec270-6e82-4f59-b3c0-172385432bd3)

大佬好，很高兴发现了这么一款优秀的流媒体服务器。
在测试RECORD插件的相关接口时，发现API暂时不能指定录制流的文件名，如果同一个流多次录制生成的文件也只有一个，是否考虑在后续迭代中允许自定义流文件名呢？点播时也可通过【streamPath + 文件名】访问到

**Comment by langhuihui** [comment]
嗯，很好的建议

**Comment by langhuihui** [comment]
在最新版本中已加入这个功能

**Comment by Johonnyr** [comment]
> 在最新版本中已加入这个功能

好的，稍后下载一下最新版体验看看[棒]
