### ISSUE TITLE
编译报 ld: warning: directory not found for option '-L/opt/homebrew/Cellar/librdkafka/1.9.2/lib'

### ISSUE THREAD

**Issue by jiangsiyij41** [langhuihui/monibuca#89]
Mac M1 pro + go1.19，服务可以启动，请问是什么位置需要请求这个库啊？

**Comment by jiangsiyij41** [comment]
<img width="718" alt="image" src="https://github.com/langhuihui/monibuca/assets/22672987/d8aed7df-bd12-41f3-98b6-0525e229f2ad">

**Comment by langhuihui** [comment]
没有用到这个库啊

**Comment by jiangsiyij41** [comment]
之前配了一个错误的LIBRARY_PATH环境变量，把它改了就可以了😅
