### ISSUE TITLE
有个需求，有没什么好办法解决？

### ISSUE THREAD

**Issue by handsometong** [langhuihui/monibuca#90]
海康摄像头配置按需拉流，业务断增加摄像头的时候需要修改配置然后重启m74服务才能生效，这会导致当时在看监控的用户监控页面断流，有没有可以不用重启m74的服务的热更新配置的方法？
<img width="959" alt="image" src="https://github.com/langhuihui/monibuca/assets/12708876/7b68e1db-ab50-4b0a-9d95-2e1145c31682">

**Comment by langhuihui** [comment]
我看一下，应该可以在api层增加动态添加功能，现在动态添加的是pullonstart里面的

**Comment by langhuihui** [comment]
下一个版本支持，我看了一下现在其实就有了，/rtsp/api/pull 这个接口参数里面带上save=2就可以，不过现在会立即开始pull。准备判断一下如果是save=2就不立即pull了，只增加到pullonsub上面

**Comment by langhuihui** [comment]
最新版已发布
