### ISSUE TITLE
编码格式为G.711U的音频打开后出现视频卡顿延迟问题

### ISSUE THREAD

**Issue by pangxiang** [langhuihui/monibuca#92]
编码格式为G.711U的音频打开后出现视频卡顿延迟问题，时不时出现reader too slow异常导致流中断，如果把G.711U的音频关闭后视频就播放流畅且不出现reader too slow异常，这个是不是ms7编解码音频有问题导致音视频不同步？

**Comment by langhuihui** [comment]
需要排查一下
