### ISSUE TITLE
下载的运行不了

### ISSUE THREAD

**Issue by wgh2019** [langhuihui/monibuca#94]
![image](https://github.com/langhuihui/monibuca/assets/51781051/4471860a-a622-4dd1-9d1f-43a48dd65a70)

**Comment by langhuihui** [comment]
需要用解压缩工具先解压缩出来

**Comment by wgh2019** [comment]
![image](https://github.com/langhuihui/monibuca/assets/51781051/df280dfd-b119-4c1a-ad9e-a29ee8863345)
是解压出来用的 双击m7s.exe

**Comment by langhuihui** [comment]
你的电脑是什么操作系统，32 位的？
