### ISSUE TITLE
哪个api可以获取到流媒体服务器上所有的流列表？

### ISSUE THREAD

**Issue by qengli** [langhuihui/monibuca#97]
我从文档中没有找到，另外服务器回调的api文档在哪里啊

**Comment by langhuihui** [comment]
api/summary

**Comment by qengli** [comment]
谢谢，另外请教一下大佬，我看最近提交的日志中有提到
[API 现在可以返回{"data":xxx,"code":0,"msg":"ok"}](https://github.com/langhuihui/monibuca/commit/4ab1f8e9a1cb7b12cf38a70dc733873de5a09cfc)
但我下载最新的代码运行时api没有返回这种格式，没有code字段，请问这个是要用配置的吗

**Comment by langhuihui** [comment]
接口后面加一个参数format=json

**Comment by langhuihui** [comment]
全局接口调试可以用这个：https://apifox.com/apidoc/shared-53418b09-8f45-49e5-94e3-1b93870b304f

**Comment by langhuihui** [comment]
请关注公众号，里面有你需要的资料。例如这个在线调试工具：https://mp.weixin.qq.com/s?__biz=MzkyMDQ5Nzg5MQ==&mid=2247483863&idx=1&sn=48867cc273794022fe816ea2b8164e38&chksm=c190ba5bf6e7334d987e5859a3bf81b8830cd409bcc40a3c3246eacf9a2f1a8dbc032e3790d1&token=1045734353&lang=zh_CN#rd

**Comment by qengli** [comment]
好的，感谢！
